# Generated by Django 5.2.9 on 2025-12-05 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='id_card_image',
            field=models.ImageField(blank=True, null=True, upload_to='id_cards/'),
        ),
        migrations.AddField(
            model_name='reservation',
            name='letter_text',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='reservation',
            name='signature_image',
            field=models.ImageField(blank=True, null=True, upload_to='signatures/'),
        ),
    ]
