# Generated by Django 5.2.9 on 2025-12-06 06:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_reservation_id_card_image_reservation_letter_text_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='feedback',
            name='computed_status',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='feedback',
            name='damage_notes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='feedback',
            name='days_late',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='feedback',
            name='loss_qty',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='reservation',
            name='actual_claimed_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='reservation',
            name='actual_return_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='reservation',
            name='behavior_score',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='reservation',
            name='missing_qty',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='reservation',
            name='never_claimed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='reservation',
            name='priority_score',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='reservation',
            name='returned_early',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='reservation',
            name='returned_qty',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='userborrower',
            name='behavior_total_score',
            field=models.IntegerField(default=0),
        ),
    ]
