# Generated by Django 5.2.9 on 2025-12-06 06:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_feedback_computed_status_feedback_damage_notes_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='event_type_weight',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='reservation',
            name='is_conflict',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='reservation',
            name='recommended_end',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='reservation',
            name='recommended_start',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='reservation',
            name='timing_weight',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='reservation',
            name='total_score',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='reservation',
            name='urgency_weight',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='userborrower',
            name='violation_count',
            field=models.IntegerField(default=0),
        ),
    ]
