# Generated by Django 5.2.9 on 2025-12-08 06:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_reservation_event_type_weight_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='feedback',
            name='computed_status',
        ),
        migrations.RemoveField(
            model_name='feedback',
            name='damage_notes',
        ),
        migrations.RemoveField(
            model_name='feedback',
            name='days_late',
        ),
        migrations.RemoveField(
            model_name='feedback',
            name='loss_qty',
        ),
        migrations.RemoveField(
            model_name='reservation',
            name='actual_claimed_date',
        ),
        migrations.RemoveField(
            model_name='reservation',
            name='actual_return_date',
        ),
        migrations.RemoveField(
            model_name='reservation',
            name='behavior_score',
        ),
        migrations.RemoveField(
            model_name='reservation',
            name='event_type_weight',
        ),
        migrations.RemoveField(
            model_name='reservation',
            name='is_conflict',
        ),
        migrations.RemoveField(
            model_name='reservation',
            name='missing_qty',
        ),
        migrations.RemoveField(
            model_name='reservation',
            name='never_claimed',
        ),
        migrations.RemoveField(
            model_name='reservation',
            name='priority_score',
        ),
        migrations.RemoveField(
            model_name='reservation',
            name='recommended_end',
        ),
        migrations.RemoveField(
            model_name='reservation',
            name='recommended_start',
        ),
        migrations.RemoveField(
            model_name='reservation',
            name='returned_early',
        ),
        migrations.RemoveField(
            model_name='reservation',
            name='returned_qty',
        ),
        migrations.RemoveField(
            model_name='reservation',
            name='timing_weight',
        ),
        migrations.RemoveField(
            model_name='reservation',
            name='total_score',
        ),
        migrations.RemoveField(
            model_name='reservation',
            name='urgency_weight',
        ),
        migrations.RemoveField(
            model_name='userborrower',
            name='behavior_total_score',
        ),
        migrations.RemoveField(
            model_name='userborrower',
            name='violation_count',
        ),
    ]
