# Generated by Django 5.2.9 on 2025-12-08 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_remove_feedback_computed_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='actual_claimed_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='reservation',
            name='actual_return_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='reservation',
            name='borrow_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='reservation',
            name='expected_return_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='reservation',
            name='priority_score',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='userborrower',
            name='behavior_score',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='damagereport',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Reviewed', 'Reviewed'), ('Resolved', 'Resolved'), ('Verified', 'Verified'), ('Settled', 'Settled')], default='Pending', max_length=20),
        ),
    ]
