# Generated by Django 5.2.9 on 2025-12-08 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_reservation_actual_claimed_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userborrower',
            name='behavior_total_score',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='userborrower',
            name='violation_count',
            field=models.IntegerField(default=0),
        ),
    ]
