# Generated by Django 5.2.9 on 2025-12-09 05:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_userborrower_behavior_total_score_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='report_type',
            field=models.CharField(choices=[('None', 'None'), ('Damage', 'Damage'), ('Loss', 'Loss')], default='None', max_length=20),
        ),
    ]
